# Generated by Django 2.2.10 on 2020-02-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_auto_20200225_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
