# Generated by Django 2.2.10 on 2020-02-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_auto_20200225_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='text',
        ),
    ]
