# Generated by Django 2.2.10 on 2020-02-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0006_auto_20200225_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='messages',
            field=models.ManyToManyField(null=True, related_name='chat_rooms', to='chat_app.Message'),
        ),
    ]
