# Generated by Django 2.2.10 on 2020-02-25 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_app', '0007_auto_20200225_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='messages',
        ),
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(null=True, related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
